[project]
name = "maya-livekit-cookbook"
version = "0.1.0"
requires-python = ">=3.12,<3.15"
dependencies = [
  "livekit-agents[silero]==1.8.0",
  "livekit-plugins-soniox==1.8.0",
  "livekit-plugins-openai==1.8.0",
  "livekit-plugins-maya @ git+https://github.com/MayaResearch/livekit-agents@b37bbeac7a5f423d1b822b04e1769d5b5f5a61e5#subdirectory=livekit-plugins/livekit-plugins-maya",
  "python-dotenv==1.2.3",
]
