[project]
name = "maya-livekit-cookbook"
version = "0.1.0"
requires-python = ">=3.12,<3.15"
dependencies = [
  "livekit-agents[silero]==1.8.0",
  "livekit-plugins-soniox==1.8.0",
  "livekit-plugins-openai==1.8.0",
  "livekit-plugins-maya @ git+https://github.com/MayaResearch/livekit-agents@fd724714bc2f0dff6653578b9f979905be9c16f6#subdirectory=livekit-plugins/livekit-plugins-maya",
  "python-dotenv==1.2.3",
]
